title: Education Planners, LLC
description: Education Planners is an educational consulting firm helping school districts across the Southeast handle organizational challenges and operate more efficiently.
tagline: Helping schools run smarter.
logo: assets/images/logo.png

url: "" # the base hostname & protocol for your site
baseurl: "/education-planners" # the subpath of your site, e.g. /blog/

# Build settings
theme: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude: ["_assets"]
keep_files: ["assets"]

collections:
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: team
    values:
      layout: resume

# seo
social:
  links:
    - https://www.facebook.com/Education-Planners-103900076340208/
