- name: "Facilities"
  icon: "facilities"
  items: |
    - Bond and Tax Referendum Preparation (Development of SPLOST Program)
    - Facility Management & Facility Plan Development
    - Demographic & Enrollment Studies
    - Classroom Utilization Studies
    - Plant Services and Facility Assessment
    - School Construction Oversight and Project Development
- name: "HR, Operations & Finance"
  icon: "hr"
  items: |
    - [Human Resources Services](!BASE_URL!/assets/images/pdf/human-resources-services.pdf){:target="_blank"}:
      -	Personnel Department Management and Organizational Structure
      - Personnel Reviews, Evaluations, and Investigations
    - Efficiency and Effectiveness Reviews
    - Personnel Department Management and Organizational Structure
    - Personnel Reviews, Evaluations, and Investigations
    - Financial Evaluation and Management, including Accounting, Reporting, and Audits
    - Communications/Public Relations audits
    - Education Planners provides additional financial accountability using [Targeted Process Solutions](https://www.linkedin.com/in/bill-winchester-10044539){:target="_blank"}. These solutions are provided by Bill Winchester, (email: bill@targetedprocesssolutions.com) who will work to enhance performance and provide financial clarity at all levels of the organization.
- name: "Coaching/Training"
  icon: "coach"
  items: |
    - [Coaching/Training Overview](!BASE_URL!/assets/images/pdf/coaching-training-overview.pdf){:target="_blank"}
    - Strategic Planning, strategy and change management
    - Local Board Governance Training
    - Leadership Training & Coaching
    - Customer Service and Communication
    - Teaching and Learning, Professional Development and Curriculum Planning
    - Program Evaluation
    - Education Planners also offers professional development and coaching using the [Strategic Instruction Model (SIM)](!BASE_URL!/assets/images/pdf/SIM-overview.pdf){:target="_blank"} and [Content Enhancement Routines](!BASE_URL!/assets/images/pdf/SIM-content-enhancement-routines.pdf){:target="_blank"}, including [SIM Learning Strategies](!BASE_URL!/assets/images/pdf/SIM-learning-strategies.pdf){:target="_blank"} and [Xtreme Reading](!BASE_URL!/assets/images/pdf/Xtreme-reading-brochure.pdf){:target="_blank"}. These courses are led by Bonnie Pasalak (email: bpalasak@gmail.com) through the University of Kansas.
