heading= "The Team"
blurb = """
The Education Planners team represents more than 200 years of combined professional experience in educational leadership. Since every school system’s challenges are different, Education Planners selects a specialized team of professionals based on an institution’s unique needs.

Whatever the challenge, the Education Planners team has been there before and has the experience to know what works - and the ability to identify and implement an appropriate solution.
"""